Update Kogito Tooling Examples
kiegroup/kogito-tooling-examples pull request #10
Opened 2020-09-10 13:55 UTC by ljmotta

2020-09-11 11:48 UTC, caponetto reviewed
Thanks for the PR, @ljmotta! Really nice samples.
I've added some minor comments after going through ~2/3 of the files.
I'll complete the review asap.

2020-09-11 11:48 UTC, caponetto commented on packages/base64png-editor-chrome-extension/package.json
> +    "url": "https://github.com/kiegroup/kogito-tooling.git"
```suggestion
    "url": "https://github.com/kiegroup/kogito-tooling-examples.git"
```

2020-09-11 11:48 UTC, caponetto commented on packages/webapp/static/resources/styles.css
> +.webapp--page-main-div {
Please add the copyright header to this file.

2020-09-11 11:48 UTC, caponetto commented on packages/webapp/static/index.html
> +  ~ Copyright 2019 Red Hat, Inc. and/or its affiliates.
```suggestion
  ~ Copyright 2020 Red Hat, Inc. and/or its affiliates.
```

2020-09-11 11:48 UTC, caponetto commented on README.md
> +This is an example that shows how to use `@kogito-tooling/*` packages APIs.
Since we have several examples in this repository, IMO the previous text seemed to make more sense.

2020-09-11 11:48 UTC, caponetto commented on packages/base64png-editor-chrome-extension/README.md
> +This is step is required, so the extension can access the envelope located on `dist/envelope/index.html`.
```suggestion
This step is required, so the extension can access the envelope located on `dist/envelope/index.html`.
```

2020-09-11 11:48 UTC, caponetto commented on packages/base64png-editor/README.md
> +This package is a Custom Editor made with React, which enables you to edit a `.base64png` file.
Really nice example!

2020-09-11 11:48 UTC, caponetto commented on packages/ping-pong-view/README.md
> +It's divided in subpackages:
```suggestion
It's divided in the following subpackages:
```

2020-09-11 11:48 UTC, caponetto commented on packages/todo-list-view-vscode-extension/.vscode/tasks.json
> +{
Can you please format this file with spaces instead of tabs?

2020-09-11 11:48 UTC, caponetto commented on packages/todo-list-view-vscode-extension/.vscode/launch.json
> +{
Can you please format this file with spaces instead of tabs?

2020-09-11 11:48 UTC, caponetto commented on packages/base64png-editor/src/styles.scss
> +.base64png-editor--page {
Please add the copyright header to this file.

2020-09-11 11:48 UTC, caponetto commented on packages/base64png-editor-vscode-extension/README.md
> +This package is the VS Code Extension, which runs the Base64 PNG Editor.
I guess we should put a note saying that it runs only on VS Code 1.46+.

2020-09-11 11:48 UTC, caponetto commented on packages/todo-list-view-vscode-extension/README.md
> +This package provides a VS Code Extension containing a 'To do' list View.
I guess we should put a note saying that it runs only on VS Code 1.46+.

2020-09-11 11:48 UTC, caponetto commented on packages/todo-list-view-vscode-extension/tsconfig.json
> +{
Can you please format this file with spaces instead of tabs?

2020-09-11 11:48 UTC, caponetto commented on packages/todo-list-view/README.md
> +It's divided in subpackages:
```suggestion
It's divided in the following subpackages:
```

2020-09-11 11:48 UTC, caponetto commented on packages/webapp/envelope/gwt-editors.html
> +<!DOCTYPE html>
Please add the copyright header to this file.

2020-09-11 11:48 UTC, caponetto commented on packages/webapp/envelope/image-editor.html
> +<!DOCTYPE html>
Please add the copyright header to this file.

2020-09-11 11:48 UTC, caponetto commented on packages/webapp/envelope/ping-pong-view-react-impl.html
> +<!DOCTYPE html>
Please add the copyright header to this file.

2020-09-11 11:48 UTC, caponetto commented on packages/webapp/envelope/todo-list-view.html
> +<!DOCTYPE html>
Please add the copyright header to this file.

2020-09-11 15:02 UTC, tiagobento commented on packages/ping-pong-view/README.md
> +It's divided in subpackages:
Replace "subpackages" with "submodules"

2020-09-11 15:03 UTC, tiagobento commented on packages/todo-list-view/README.md
> +It's divided in subpackages:
Same here.

2020-09-11 19:16 UTC, ljmotta commented
@caponetto Thanks for your review!! I've done the adjustments

2020-09-14 16:25 UTC, caponetto approved these changes
Again, pretty cool examples! I have one suggestion, though:
IMO it'd be nice to have an image or a short gif on each readme file showing the example, wdyt?
@ljmotta @tiagobento

2020-09-14 17:57 UTC, tiagobento commented
Agreed @caponetto. @ljmotta Can you please add a GIF to each of the examples showing a basic usage of them?

2020-09-14 19:56 UTC, ljmotta commented
@caponetto @tiagobento Sure!

2020-10-09 08:58 UTC, tiagobento requested changes

2020-10-09 08:58 UTC, tiagobento commented on packages/todo-list-view/src/embedded/EmbeddedTodoList.tsx
> +      markAllAsCompleted: () => envelopeServer.manager.clientApi.notifications.todoList__markAllAsCompleted(),
You can use `enveloepServer.envelopeApi` directly.

2020-10-14 14:22 UTC, ederign approved these changes

2020-10-14 14:33 UTC, tiagobento approved these changes

2020-10-14 14:35 UTC, merged